### ISSUE TITLE
Patches provided are not proper patches

### ISSUE THREAD

**Issue by ndufresne** [paolo-pr/laav#1]
Instead of providing proper patches, this project provides full C files. This is will prevent blending these changes with newer version of GStreamer. As a side effect, it will be hard for users to integrate later security fixes and bug fixes and may be included in these forks.

**Comment by paolo-pr** [comment]
I agree that patches are generally better, but the directores where full modified C files are put are marked with a precise gstreamer/ffmpeg version (then, the user of the project is adviced to do a preliminary check of the version of the libraries he is installing, before doing undesiderated blending). I preferred to put the full C files so that the user can soon see the full code where modifications must be done. In addition, I hope that I'll remove these patches ASAP and replace them with proper custom plugins.

**Comment by paolo-pr** [comment]
I changed idea meanwhile and added standard patches

**Comment by ndufresne** [comment]
Thanks.
